# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 01:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_response', models.DateField(default=datetime.datetime.now)),
                ('int_response', models.IntegerField(blank=True, null=True)),
                ('float_response', models.FloatField(blank=True, null=True)),
                ('date_response', models.DateField(blank=True, null=True)),
                ('boolean_response', models.NullBooleanField()),
                ('text_response', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('show_name', models.BooleanField(default=True)),
                ('allow_custom_responses', models.BooleanField(default=False)),
                ('default_boolean_resp', models.NullBooleanField()),
                ('default_date_resp', models.DateField(blank=True, null=True)),
                ('default_text_resp', models.CharField(blank=True, max_length=60, null=True)),
                ('default_int_resp', models.IntegerField(blank=True, null=True)),
                ('default_float_resp', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ui', models.CharField(choices=[('radio', 'radio'), ('check', 'check'), ('box', 'box'), ('bigbox', 'bigbox')], max_length=20)),
                ('datatype', models.CharField(choices=[('int', 'int'), ('text', 'text')], max_length=20)),
                ('choices', models.ManyToManyField(related_name='choice_groups', to='db.Choice')),
            ],
        ),
        migrations.CreateModel(
            name='kwargs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('birthdate', models.DateField()),
                ('studyid', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('prompt', models.CharField(max_length=200)),
                ('allow_multiple_responses', models.BooleanField()),
                ('missing_value_int', models.IntegerField(blank=True, default=999, null=True)),
                ('missing_value_float', models.FloatField(blank=True, null=True)),
                ('missing_value_boolean', models.NullBooleanField()),
                ('missing_value_date', models.DateField(blank=True, null=True)),
                ('missing_value_text', models.CharField(blank=True, max_length=60, null=True)),
                ('choice_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Choice_Group')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='db.Person')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='db.Person')),
            ],
        ),
        migrations.CreateModel(
            name='sourceChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60)),
                ('equivalent_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Choice')),
            ],
        ),
        migrations.CreateModel(
            name='sourceColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_header', models.CharField(max_length=200)),
                ('missing_value', models.CharField(blank=True, default='999', max_length=100, null=True)),
                ('valid_values', models.ManyToManyField(related_name='sourceColumns', to='db.sourceChoices')),
            ],
        ),
        migrations.CreateModel(
            name='SourceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_func', models.CharField(max_length=80)),
                ('args', models.ManyToManyField(related_name='SourceQuestions', to='db.kwargs')),
            ],
        ),
        migrations.CreateModel(
            name='SourceScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceQuestions', models.ManyToManyField(related_name='sourceSchemes', to='db.SourceQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surveytype', models.CharField(choices=[('observational', 'observational'), ('self report', 'self report')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Survey_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Survey')),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Measure')),
            ],
        ),
        migrations.AddField(
            model_name='sourcescheme',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Survey'),
        ),
        migrations.AddField(
            model_name='sourcequestion',
            name='question_equivalent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Survey_Question'),
        ),
        migrations.AddField(
            model_name='sourcequestion',
            name='source_columns',
            field=models.ManyToManyField(related_name='sourceQuestions', to='db.sourceColumn'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent', to='db.Person'),
        ),
        migrations.AddField(
            model_name='answer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='db.Person'),
        ),
        migrations.AddField(
            model_name='answer',
            name='survey_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Survey_Question'),
        ),
        migrations.AlterUniqueTogether(
            name='survey_question',
            unique_together=set([('survey', 'question_order')]),
        ),
    ]
