# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='ui',
        ),
        migrations.AddField(
            model_name='choice_group',
            name='ui',
            field=models.CharField(default='radio', max_length=20),
            preserve_default=False,
        ),
    ]
