# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_choice_group_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_question',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Measure'),
        ),
    ]
