# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_question_allow_multiple_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='missing_value_boolean',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='question',
            name='missing_value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='missing_value_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='missing_value_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='missing_value_text',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
