# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20161021_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='db.Person')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='db.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='missing_value_int',
            field=models.IntegerField(blank=True, default=999, null=True),
        ),
    ]
